name: miniaudio
description: Flutter bindings for Miniaudio Library.
version: 0.0.1
homepage: https://github.com/Piero512/miniaudio_decoder

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  ffi: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  ffigen: ^4.1.3
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: dev.piero512.miniaudio
        pluginClass: MiniaudioPlugin
      ios:
        pluginClass: MiniaudioPlugin
      macos: 
        pluginClass: MiniaudioPlugin
      linux:
        pluginClass: MiniaudioPlugin
      windows:
        pluginClass: MiniaudioPlugin

ffigen:
  output: 'lib/src/miniaudio_ffi.dart'
  headers:
    entry-points:
      - 'src/miniaudio.h'
    include-directives:
      - '**miniaudio.h'
  name: 'MiniAudioFfi'
  preamble: '// ignore_for_file: camel_case_types, non_constant_identifier_names'
  unions:
    dependency-only: opaque
  description: 'FFI bindings to miniaudio library'